spring.application.name=api-gateway
server.port=8765

#eureka.client.enabled=false
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG